config/routes.rb
Rails.application.routes.draw do
  get 'sections/show'

  resources :pre_survey_travel_patterns
  resources :pre_surveys do
    collection do
      get :new_tourist
      get :new_resident
    end
  end

  # SP Experiment
  resources :sp_experiments do
    resource :activity_choices
    resource :day_to_day_learnings
    resources :day_choices
  end

  # Pre-survey
  resources :pre_survey_journey_planner_characteristics
  resources :pre_survey_private_mobility_characteristics
  # resources :pre_survey_household_characteristics
  resources :pre_survey_socio_economic_characteristics
  match 'pre_questionnaire' => 'pre_survey_socio_economic_characteristics#new', :via => [:post, :get]
  match 'finish_presurvey' => 'pre_survey_journey_planner_characteristics#finish_presurvey', :via => [:post, :get]
  
  resources :tests

  # Users section
  resource :users, only: [:new, :create, :update] do
    patch :update_password, on: :member
    post :submitIgnorePopup
    post :acknowledge_warning
    get :dismiss_timezone_warnings
    get :update_wsp_email
    get :new_wsp
    get :sync_umove
  end

  resources :users do
    member do
      get :screenout
    end
  end

  get 'users/:study/new' => 'users#new', as: :new_users_for_study
  post 'users/:study' => 'users#create', as: :users_for_study

  resource :user_session, only: [:create, :destroy] do
    post :change_timezone
  end

  namespace :activations do
    get :new
    get ":activation_code", action: :create
    post :resend, as: :resend
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :sections do
    get :next_section, on: :collection
  end

  # get "/wsp_register" => "users#new_wsp"

  # Static pages and AD section

  namespace :pages do
    get :home
    get :new_home
    get :thankyou
    get :newuser
    get :calendar
    post :calendar
    get :feedback_feedback
    get :consent
    get :contacts
    get :faqs
    get :dashboard
    get :support
    post :support_submit
    patch :accept_consent
    patch :deactivate_user
    # root to: :index # BEFORE
    get :info
    get :overview
    get :image_test
    root action: :index
    get :wsp
    get :disclaimer
    get :statistics
    get :summarise
    get :backoffice_container
    get :backoffice
    get :tab_1
    get :tab_2
    # get :tab_3
    get :tab_3_1
    get :tab_3_2
    get :tab_3_3
    get :gateway
    post :survey
  end

  match "/delayed_job" => DelayedJobWeb, anchor: false, via: [:get, :post]#, constraints: AdminConstraint.new

  root :to => 'pages#survey'
end

app/views/partials/_change_locale.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    = I18n.t('menu.select_language')
    %span.caret
  %ul.dropdown-menu{:role => "menu"}
    %li
      = link_to I18n.t('menu.languages.english'), root_path(locale: :en, current_page: request.url)
    %li
      = link_to I18n.t('menu.languages.chinese'), root_path(locale: :zh, current_page: request.url)
    %li
      = link_to I18n.t('menu.languages.hebrew'), root_path(locale: :he, current_page: request.url)

app/views/partials/_change_timezone.html.haml
.time_zone_globe
.time_zone_panel
  .arrow-up
  %h2 Your time zone
  = form_tag(change_timezone_user_session_path, method: :post) do
    .form-group
      = time_zone_select( "user", "time_zone" , ActiveSupport::TimeZone.all, :default => session[:time_zone])
    .form-group
      = hidden_field_tag 'goto', "#{request.url}"
    %hr/
    Click anywhere outside this area to dismiss
:javascript
  jQuery("#user_time_zone").change(function(){
  		if (jQuery(".form-group input[name=goto]").val() != "#{request.url}") {
  			jQuery(".form-group input[name=goto]").val("/report/"+smart.Diary._selectedDay);
  		};
  		//submit timezone change
  		jQuery("#user_time_zone").closest("form").submit();
  		$(".time_zone_panel").animate({'visibility':'hidden', 'opacity': 0, 'z-index': 0}, 500);
  	});
  
  	$(".time_zone_globe").hover(function(e){
  		$(".time_zone_panel").css({'visibility':'visible', 'opacity': 1, 'z-index': 1000});
  	});
  
  	$(document).click(function (e) {
      e.stopPropagation();
      if ($(".time_zone_panel").has(e.target).length === 0) {
       	$(".time_zone_panel").animate({'visibility':'hidden', 'opacity': 0, 'z-index': 0}, 500);
      }
  	});

app/views/partials/_frequent_places.html.haml
:javascript
  var tempBounds = new google.maps.LatLngBounds();
    var pos = null;
    var infowindow;
    var lastPos;
  
    jQuery(document).ready(function(){
      smart.Map.loadFrequentPlacesMap();
  
  <haml_silent>     current_user.frequent_places.includes(:user_activities).each do |p| 
  </haml_silent><haml_block>      pos = new google.maps.LatLng( #{p.lat}, #{p.lon});
        tempBounds.extend(pos);
  <haml_silent>       p.user_activities.each do |a| 
  </haml_silent><haml_block>        smart.Map.addFrequentPlaceToMap(smart.Map._frequentPlacesMap,pos,"#{a.name}", #{p.id}, #{a.id}, "#{a.image}");
  </haml_block></haml_block>
      smart.Map._frequentPlacesMap.fitBounds(tempBounds);
  
      jQuery('#add_frequent_place_submit').bind('click', function(ev){
        if (smart.Map._tempMarker === null) {
          alert('Please set a location first.');
        }
        else {
          smart.Map.addFrequentPlace();
          // update the table too
        }
      });
  
      jQuery('.address_autocomplete').on('keydown', function(e) {
        if(e.keyCode == 13) { // enter key was pressed
          e.preventDefault();
        }
      });
    });
.control-group.column-group
  .alert_container
  %div
    %p Please tell us about some of your frequently visited places. This will make it easier for us to interpret and for you to review your location data.
  /
    <div class="large-30" id="select_place_type">
    <haml_silent>     PlaceCategory.all.each do |p|
    </haml_silent><haml_block>      <haml_loud> radio_button_tag :place_category_id, p.id, p.name, label: p.name </haml_loud>
    <haml_loud> label :place_category, p.name </haml_loud>
    </haml_block>  </div>
.clear
.ink-form
  .control-group.column-group
    .large-50
      .column-group
        %label 1. Select the primary activity type:
        %select#frequent_place_user_activity_id
          = options_for_select(UserActivity.all.map{ |a| [a.name, a.id, {image: a.image}] })
  .control-group.column-group
    .large-100
      %label 2. Enter/search for an address, location or place name:
      %input#add_frequent_place_search.address_autocomplete{:name => "address_input", :type => "text", :value => ""}/
  .control-group.column-group
    .large-60
      .column-group
        %label 3. Adjust temporary location marker in map by moving it if not accurately placed
    .large-20
      %input#add_frequent_place_submit.setMarkerButton.btn{:type => "button", :value => "Add frequent place"}/
  %p *To delete, right-click on an existing marker, or click on 'X' in the corresponding table row.
  .control-group.column-group
    .large-50
      #frequent_places_map Map div goes here
    #frequent_places_table.ink-table.large-50
      = render 'frequent_places/table'

app/views/partials/_section.html.haml
= div_for @section, :class => @section.custom_class do
  - qs ||= []
  - (questions = @section.questions).each_with_index do |q, i|
    - if q.part_of_group?
      - qs << q # gather up the group questions
      - if (i+1 >= questions.size) or (q.question_group_id != questions[i+1].question_group_id)
        - # this is the last question of the section, or the group
        = render q.question_group.custom_renderer || "/partials/question_group", :g => q.question_group, :qs => qs, :f => f
        - qs = []
    - else # gather up the group questions
      = render q.custom_renderer || "/partials/question", :q => q, :f => f

app/views/partials/_timezone_switch.html.haml
- if timezone_switch
  - if current_user.show_timezone_warnings?
    #flash_messages.timezone_switch
      %p.content_feedback_warning
        Change timezone to
        = succeed "?" do
          %span#suggested_tz= timezone_switch[:description]
        %span.inline_options
          %a#change_tz{:href => "#"} Yes
          %a#dismiss_tz{:href => "#"} No
          = link_to "Don't ask again", dismiss_timezone_warnings_users_path
    :javascript
      jQuery("#change_tz").click(function () {
      	var matching_timezone = $("#user_time_zone option:contains('#{timezone_switch[:formatted_offset]}'):first").val();
      	$("#user_time_zone").val(matching_timezone).change();
      });

      jQuery("#dismiss_tz").click(function () {
      	jQuery(".timezone_switch").fadeOut(500);
      });

      var matching_timezone = $("#user_time_zone option:contains('#{timezone_switch[:formatted_offset]}'):first").text();
      $("#suggested_tz").html(matching_timezone);