config/routes.rb
Rails.application.routes.draw do
  get 'sections/show'

  resources :pre_survey_travel_patterns
  resources :pre_surveys do
    collection do
      get :new_tourist
      get :new_resident
    end
  end

  # SP Experiment
  resources :sp_experiments do
    resource :activity_choices
    resource :day_to_day_learnings
    resources :day_choices
  end

  # Pre-survey
  resources :pre_survey_journey_planner_characteristics
  resources :pre_survey_private_mobility_characteristics
  # resources :pre_survey_household_characteristics
  resources :pre_survey_socio_economic_characteristics
  match 'pre_questionnaire' => 'pre_survey_socio_economic_characteristics#new', :via => [:post, :get]
  match 'finish_presurvey' => 'pre_survey_journey_planner_characteristics#finish_presurvey', :via => [:post, :get]
  
  resources :tests

  # Users section
  resource :users, only: [:new, :create, :update] do
    patch :update_password, on: :member
    post :submitIgnorePopup
    post :acknowledge_warning
    get :dismiss_timezone_warnings
    get :update_wsp_email
    get :new_wsp
    get :sync_umove
  end

  resources :users do
    member do
      get :screenout
    end
  end

  get 'users/:study/new' => 'users#new', as: :new_users_for_study
  post 'users/:study' => 'users#create', as: :users_for_study

  resource :user_session, only: [:create, :destroy] do
    post :change_timezone
  end

  namespace :activations do
    get :new
    get ":activation_code", action: :create
    post :resend, as: :resend
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :sections do
    get :next_section, on: :collection
  end

  # get "/wsp_register" => "users#new_wsp"

  # Static pages and AD section

  namespace :pages do
    get :home
    get :new_home
    get :thankyou
    get :newuser
    get :calendar
    post :calendar
    get :feedback_feedback
    get :consent
    get :contacts
    get :faqs
    get :dashboard
    get :support
    post :support_submit
    patch :accept_consent
    patch :deactivate_user
    # root to: :index # BEFORE
    get :info
    get :overview
    get :image_test
    root action: :index
    get :wsp
    get :disclaimer
    get :statistics
    get :summarise
    get :backoffice_container
    get :backoffice
    get :tab_1
    get :tab_2
    # get :tab_3
    get :tab_3_1
    get :tab_3_2
    get :tab_3_3
    get :gateway
    post :survey
  end

  match "/delayed_job" => DelayedJobWeb, anchor: false, via: [:get, :post]#, constraints: AdminConstraint.new

  root :to => 'pages#survey'
end

app/controllers/users_controller.rb
require 'mail_officer'

class UsersController < ApplicationController
  layout 'smart'

  # before_filter :require_no_user, only: [:new, :create, :new_wsp]

  def new
    @user = User.new
  end

  def new_wsp
    @user = User.new
    @user.rn_id = params[:rn_id]
    @user.rn_study = params[:rn_study]
  end

  def update_wsp_email
    current_user.wsp_email = params[:wsp_email]
    if current_user.save
      render status: :ok
    else
      render status: :bad_request
    end
  end

  def sync_umove
    # Check if user already exists
    if params[:umove_id]
      @user = User.where(umove_id: params[:umove_id]).first
    end

    if @user.blank?
      @user = User.new_guest
      @user.city_id = params[:city_id]
      @user.umove_id = params[:umove_id]
      @user.user_type = "resident"
      @user.survey_email_start = params[:user_email] || ""

      # RN
      @user.rn_id = params[:rn_id]
      @user.rn_study = params[:rn_study]

      # Set browser
      browser = Browser.new(request.env['HTTP_USER_AGENT'], accept_language: "en-us")
      @user.browser = browser.name
      @user.ip_address = request.remote_ip
      if browser.device.mobile?
        @user.device = User::MOBILE
      elsif browser.device.tablet?
        @user.device = User::TABLET
      else
        @user.device = User::DESKTOP
      end

      @user.registration_source = 'web'
      @user.participating = true
      @user.save!(context: :human)
      @user.activate!
      @user.consent!
    end

    # Update MAN survey pre-screening answers #
    if params[:user_screen_responses]
      # Smartphone
      if params[:user_screen_responses][:smart_phone] and params[:user_screen_responses][:smart_phone] == "0"
        @user.screenout!
        redirect_to "http://endlinks.researchnow.com/d?status=2&rnid=#{@user.rn_id}&study=#{@user.rn_study}"
        return
      end

      # Age
      # 30%  18-30 years old
      # 35%  31-45 years old
      # 30%  46-60 years old
      # 5%   More than 61 years old
      if params[:user_screen_responses][:age]
        age = params[:user_screen_responses][:age].to_i
        # Set rn_age
        @user.rn_age = age
        @user.save

        if age < 18
          @user.screenout!
          redirect_to "http://endlinks.researchnow.com/d?status=2&rnid=#{@user.rn_id}&study=#{@user.rn_study}"
          return
        end

        # Check quota
        if User.check_quota_age(age)
          pre_survey_socio_economic_characteristic = PreSurveySocioEconomicCharacteristic.new(user_id: @user.id)
          pre_survey_socio_economic_characteristic.age = age
          pre_survey_socio_economic_characteristic.save(validate: false)
        else
          Rails.logger.debug "SURVEY-DEBUG: Overquota -> AGE"
          # 3.3
          @user.overquota!(3.3)
          redirect_to "http://endlinks.researchnow.com/d?status=3&rnid=#{@user.rn_id}&study=#{@user.rn_study}"
          return
        end
      end

      # Sex
      # 50/50 gender spilt
      if params[:user_screen_responses][:sex]
        sex = params[:user_screen_responses][:sex].to_i
        # Set rn_sex
        @user.rn_sex = sex
        @user.save

        # Check quota
        if User.check_quota_sex(sex)
          if @user.pre_survey_socio_economic_characteristic
            pre_survey_socio_economic_characteristic = @user.pre_survey_socio_economic_characteristic
          else
            pre_survey_socio_economic_characteristic = PreSurveySocioEconomicCharacteristic.new(user_id: @user.id)
          end

          pre_survey_socio_economic_characteristic.sex = sex
          pre_survey_socio_economic_characteristic.save(validate: false)
        else
          Rails.logger.debug "SURVEY-DEBUG: Overquota -> SEX"
          # 3.2
          @user.overquota!(3.2)
          redirect_to "http://endlinks.researchnow.com/d?status=3&rnid=#{@user.rn_id}&study=#{@user.rn_study}"
          return
        end
      end

      # Licences
      # At least 60% to have a driving license
      licences = [
        params[:user_screen_responses][:licence_car],
        params[:user_screen_responses][:licence_motorcycle],
        params[:user_screen_responses][:licence_none]
      ]
      licences.compact!
      if not licences.empty?
        # Set rn_licence
        if licences.include?("1") or licences.include?("2")
          @user.rn_licence = 1
        else
          @user.rn_licence = 0
        end
        @user.save

        # Check quota
        if User.check_quota_licence(@user.rn_licence)
          pre_survey_private_mobility_characteristic = PreSurveyPrivateMobilityCharacteristic.new(user_id: @user.id)
          pre_survey_private_mobility_characteristic.driving_licences = licences.to_s
          pre_survey_private_mobility_characteristic.save(validate: false)
        else
          Rails.logger.debug "SURVEY-DEBUG: Overquota -> LICENCE"
          # 3.1
          @user.overquota!(3.1)
          redirect_to "http://endlinks.researchnow.com/d?status=3&rnid=#{@user.rn_id}&study=#{@user.rn_study}"
          return
        end
      end
    end

    # Update city_id (if needed)
    if params[:city_id] != @user.city_id
      @user.city_id = params[:city_id]
      @user.save!(context: :human)
    end

    # Autmatically login the user and redirect to overview
    # @user_session = UserSession.new(params[:user])
    @user_session = UserSession.new(@user)
    if @user_session.save!
      session[:time_zone] = @user_session.record.time_zone

      locale = "en"
      if @user.city_id == City::BUDAPEST
        locale = "hu"
      end

      if @user.city_id == City::TURIN
        if params[:lux_language] == "2"
          locale = "de"
        elsif params[:lux_language] == "3"
          locale = "fr"
        end
      end

      sp_experiment = @user.sp_experiment || SpExperiment.create(user_id: @user.id)
      # redirect_to new_sp_experiment_activity_choices_path(sp_experiment_id: sp_experiment)
      redirect_to next_section_sections_path
    else
      redirect_to "http://195.251.134.191/mainmain.php"
    end
  end

  def create
    # @user = params[:user] ? User.new(params[:user]) : User.new_guest
    if params[:user]
      @user = User.new(params[:user])
    else
      @user = User.new_guest
      @user.rn_id = params[:rn_id]
      @user.rn_study = params[:rn_study]
      @user.city_id = params[:city_id]
      @user.umove_id = params[:umove_id]
    end

    # Set browser
    browser = Browser.new(request.env['HTTP_USER_AGENT'], accept_language: "en-us")
    @user.browser = browser.name

    @user.registration_source = 'web'
    @user.participating = true
    if @user.save!(context: :human)
      @user.activate!
      @user.consent!

      # Autmatically login the user and redirect to overview
      # @user_session = UserSession.new(params[:user])
      @user_session = UserSession.new(@user)
      if @user_session.save!
        session[:time_zone] = @user_session.record.time_zone
        # redirect_to new_sp_experiment_url
        locale = "en"
        if @user.city_id == City::BUDAPEST
          locale = "hu"
        end

        redirect_to pre_questionnaire_url(locale: locale)
        # redirect_to pages_disclaimer_url
      else
        redirect_to root_url
      end
    else
      flash[:notice] = I18n.t('account.create_unsuccessful')
      flash[:class] = "content_error"

      if params[:wsp]
        render :action => 'new_wsp', :id => params[:user][:panelist_secure_id]
      else
        render :action => 'new'
      end
    end
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = I18n.t('profile.update_successful')
      flash[:class] = "content_feedback"
      redirect_to pages_dashboard_path
    else
      render :action => 'edit'
    end
  end

  def update_password
    if current_user.valid_password? params[:user][:current_password]
      current_user.password = params[:user][:password]
      current_user.password_confirmation = params[:user][:password_confirmation]
      if current_user.save
        flash[:passwdupdated] = I18n.t('profile.passwd_successfully_changed')
        flash[:class] = "content_feedback"
        redirect_to pages_dashboard_path, notice: 'Your password has been updated'
      else
        flash[:passwdupdated] = I18n.t('profile.error_updating_password')
        flash[:class] = "content_error"
        redirect_to pages_dashboard_path
      end
    else
      flash[:passwdupdated] = I18n.t('profile.current_passwd_invalid')
      flash[:class] = "content_error"
      redirect_to pages_dashboard_path
    end
  end

  def screenout
    @user = User.find(params[:id])
    @user.screenout!

    redirect_to "http://endlinks.researchnow.com/d?rnid=#{@user.rn_id}&study=#{@user.rn_study}&status=2"
  end

  def submitIgnorePopup
    current_user.updatePromptProperty(params["dialogname"])
    render :nothing => true
  end

  def acknowledge_warning
    current_user.acknowledge_warning
    render :nothing => true
  end

  def dismiss_timezone_warnings
    dismiss = current_user.user_property.where(name: "dismiss_timezone_warnings").first_or_initialize

    if !dismiss.value.nil?
      dismiss.value = (dismiss.value == "0" ? "1" : "0")
    else
      dismiss.value = "1"
    end
    dismiss.save

    redirect_to pages_home_url
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def study_title
    if params[:study].present?
      content_tag(:h4, "You are signing up for the #{params[:study]} study")
    end
  end

  def study_field
    if params[:study].present?
      hidden_field_tag('user[study]', params[:study])
    end
  end

  def create_user_url
    if params[:study].present?
      users_for_study_url(params[:study])
    else
      users_url
    end
  end
end

app/views/users/new.html.haml
.grid_12.form_user
  = study_title
  %h2.title_1 Create your account
  .h2_small Help us in our research by registering in the project.
  = form_for @user, :html => {:class=> 'register_form'}, url: create_user_url do |form|
    %div
      = study_field
      .form-group
        %label.hide{:for => "fullName"} Name
        %input#fullName.form-control{:name => "user[name]", :placeholder => "#{I18n.t('newuser.name')}", :type => "text", :value => "#{@user.name}"}/
        - if @user.errors[:name]
          %span.error= @user.errors[:name].join("; ")
      .form-group
        %label.hide{:for => "emailAddress"} Email
        %input#emailAddress.form-control{:name => "user[email]", :placeholder => "#{I18n.t('newuser.email')}", :type => "email", :value => "#{@user.email}"}/
        - if @user.errors[:email]
          %span.error= @user.errors[:email].join("; ")
        %p.help-block.error Warning: email is needed for password reset!
      .form-group
        %label.hide{:for => "username"} Username
        %input#username.form-control{:name => "user[username]", :placeholder => "Username", :type => "text", :value => "#{@user.username}"}/
        - if @user.errors[:username]
          %span.error= @user.errors[:username].join("; ")
      .form-group
        %label.hide{:for => "inputPassword"} Password
        %input#inputPassword.form-control{:name => "user[password]", :placeholder => "#{I18n.t('newuser.passwd')}", :type => "password"}/
        - if @user.errors[:password]
          %span.error= @user.errors[:password].join("; ")
      .form-group
        %label.hide{:for => "confirmPassword"} Confirm 
        %input#confirmPassword.form-control{:name => "user[password_confirmation]", :placeholder => "#{I18n.t('newuser.passwd_confirm')}", :type => "password"}/
        - if @user.errors[:password_confirmation]
          %span.error= @user.errors[:password_confirmation].join("; ")
      .form-group
        %label{:for => "user_time_zone"} Choose your time zone:
        = form.time_zone_select(:time_zone, ActiveSupport::TimeZone.all, {:default => session[:time_zone], prompt: "Please select your timezone:"})
        - if @user.errors[:time_zone]
          %span.error= @user.errors[:time_zone].join("; ")
      .form-group
        %label.hide{:for => "register_button"}  
        %input.bigbutton{:name => "register_submit", :type => "submit", :value => "Create account"}/
:javascript
  jQuery(document).ready(function(){
  
  if(!Modernizr.input.placeholder){
  
  	jQuery('.form_user label').each(function(idx,obj){
  		elm = jQuery(obj)
  		elm.show();
  		elm.removeClass('hide');
  	})
  
  }
  
  });

app/views/users/new_wsp.html.haml
.row
  / ROW
  .col-md-offset-1.col-md-5.form_user
    %h3.title_1
    %p Create your account
    = form_for @user, :html => {:class=> 'register_form'}, url: create_user_url do |form|
      = form.hidden_field :rn_id
      = form.hidden_field :rn_study
      = form.hidden_field :time_zone, value: "London"
      = hidden_field_tag "wsp", true
      %div
        = study_field
        .form-group
          %label.hide{:for => "username"} Username
          %input#username.form-control{:name => "user[username]", :placeholder => "Username", :type => "text", :value => "#{@user.username}"}/
          - if @user.errors[:username]
            %span.error= @user.errors[:username].join("; ")
        .form-group
          %label.hide{:for => "emailAddress"} Email
          %input#emailAddress.form-control{:name => "user[email]", :placeholder => "#{I18n.t('newuser.email')}", :type => "email", :value => "#{@user.email}"}/
          - if @user.errors[:email]
            %span.error= @user.errors[:email].join("; ")
          %p.help-block We only need your email in case you need to reset your password, we promise not to send you any spam.
        .form-group
          %label.hide{:for => "inputPassword"} Password
          %input#inputPassword.form-control{:name => "user[password]", :placeholder => "#{I18n.t('newuser.passwd')}", :type => "password"}/
          - if @user.errors[:password]
            %span.error= @user.errors[:password].join("; ")
        .form-group
          %label.hide{:for => "confirmPassword"} Confirm 
          %input#confirmPassword.form-control{:name => "user[password_confirmation]", :placeholder => "#{I18n.t('newuser.passwd_confirm')}", :type => "password"}/
          - if @user.errors[:password_confirmation]
            %span.error= @user.errors[:password_confirmation].join("; ")
        .form-group.text-center
          %label.hide{:for => "register_button"}  
          %input.bigbutton{:name => "register_submit", :type => "submit", :value => "Create account and log in"}/
  #wsp-info.col-md-offset-1.col-md-5
    #login_section
      .login_section
        - @user_session = UserSession.new
        = form_for @user_session, :url => user_session_path, :html => {:class=>"form_login form_user", :name=>"form_login"} do |f|
          %table.col-xs-12
            %tr
              %td{:colspan => "2", :style => "padding: 5px"}
                %h5.content_5.title_1 If you already have an LMS account, please log in
            %tr
              %td{:colspan => "2"}
                %label.hide{:for => "user_session_email"} Email
                %input#user_session_email.col-xs-12{:name => "user_session[username]", :placeholder => "Username/Email", :size => "31", :type => "text"}/
            %tr
              %td{:colspan => "2"}
                %label.hide{:for => "user_session_password"} Password
                %input#user_session_password.col-xs-12{:name => "user_session[password]", :placeholder => "Password", :size => "31", :type => "password"}/
            %tr
              %td
                %input.bigbutton{:name => "login_submit", :type => "submit", :value => "Login"}/
                %br/
                = link_to I18n.t('newuser.forgot_passwd') , new_password_reset_path
              %td
/ END OF ROW
:javascript
  jQuery(document).ready(function(){
  
  if(!Modernizr.input.placeholder){
  
    jQuery('.form_user label').each(function(idx,obj){
      elm = jQuery(obj)
      elm.show();
      elm.removeClass('hide');
    })
  
  }
  
  });
:css
  #wsp-info p {
    text-align: justify;
  }