config/routes.rb
Rails.application.routes.draw do
  get 'sections/show'

  resources :pre_survey_travel_patterns
  resources :pre_surveys do
    collection do
      get :new_tourist
      get :new_resident
    end
  end

  # SP Experiment
  resources :sp_experiments do
    resource :activity_choices
    resource :day_to_day_learnings
    resources :day_choices
  end

  # Pre-survey
  resources :pre_survey_journey_planner_characteristics
  resources :pre_survey_private_mobility_characteristics
  # resources :pre_survey_household_characteristics
  resources :pre_survey_socio_economic_characteristics
  match 'pre_questionnaire' => 'pre_survey_socio_economic_characteristics#new', :via => [:post, :get]
  match 'finish_presurvey' => 'pre_survey_journey_planner_characteristics#finish_presurvey', :via => [:post, :get]
  
  resources :tests

  # Users section
  resource :users, only: [:new, :create, :update] do
    patch :update_password, on: :member
    post :submitIgnorePopup
    post :acknowledge_warning
    get :dismiss_timezone_warnings
    get :update_wsp_email
    get :new_wsp
    get :sync_umove
  end

  resources :users do
    member do
      get :screenout
    end
  end

  get 'users/:study/new' => 'users#new', as: :new_users_for_study
  post 'users/:study' => 'users#create', as: :users_for_study

  resource :user_session, only: [:create, :destroy] do
    post :change_timezone
  end

  namespace :activations do
    get :new
    get ":activation_code", action: :create
    post :resend, as: :resend
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :sections do
    get :next_section, on: :collection
  end

  # get "/wsp_register" => "users#new_wsp"

  # Static pages and AD section

  namespace :pages do
    get :home
    get :new_home
    get :thankyou
    get :newuser
    get :calendar
    post :calendar
    get :feedback_feedback
    get :consent
    get :contacts
    get :faqs
    get :dashboard
    get :support
    post :support_submit
    patch :accept_consent
    patch :deactivate_user
    # root to: :index # BEFORE
    get :info
    get :overview
    get :image_test
    root action: :index
    get :wsp
    get :disclaimer
    get :statistics
    get :summarise
    get :backoffice_container
    get :backoffice
    get :tab_1
    get :tab_2
    # get :tab_3
    get :tab_3_1
    get :tab_3_2
    get :tab_3_3
    get :gateway
    post :survey
  end

  match "/delayed_job" => DelayedJobWeb, anchor: false, via: [:get, :post]#, constraints: AdminConstraint.new

  root :to => 'pages#survey'
end

app/views/pages/_tutorial.en.html.haml
#tutorial.clearfix
  #controls.breadcrumbs_holder
    %table{:cellpadding => "0", :cellspacing => "0"}
      %tr
        %td#breadcrumb_step_1.breadcrumb.current_step= link_to_function 'Step 1', "nextStep('', 'step_1');"
        %td#breadcrumb_step_2_android.breadcrumb{:style => ""}= link_to_function 'Step 2', "nextStep('', 'step_2_android');"
        %td#breadcrumb_step_3_android.breadcrumb.final_step{:style => ""}= link_to_function 'Step 3', "nextStep('', 'step_3_android');"
    /
      <span id="breadcrumb_step_1" class="breadcrumb current_step" style="width:30%"><haml_loud> link_to_function &#39;Step 1&#39;, &quot;nextStep(&#39;&#39;, &#39;step_1&#39;);&quot;</haml_loud></span>
      <span id="breadcrumb_step_2_android" class="breadcrumb" style="display:none;width:35%"><haml_loud> link_to_function &#39;Step 2&#39;, &quot;nextStep(&#39;&#39;, &#39;step_2_android&#39;);&quot;</haml_loud></span>
      <span id="breadcrumb_step_3_android" class="breadcrumb final_step" style="display:none;width:35%"><haml_loud> link_to_function &#39;Step 3&#39;, &quot;nextStep(&#39;&#39;, &#39;step_3_android&#39;);&quot;</haml_loud></span>
  #step_1.tutorial_steps
    .clear
    .grid_3
      %p.title_1
        %b Step 1
        —  Download
        = succeed "the" do
          %br/
      %br/
    .grid_4
      %p.title_1 Android
      %p.content_1
        FM Survey is a free application for Android phones.
        = succeed "Download" do
          %br/
        = succeed "from" do
          %br/
      %p.content_b  
      %a{:href => "https://play.google.com/store/apps/details?id=edu.mit.smart.fmsurvey.android"}
        %img{:height => "40", :src => "http://www.android.com/images/brand/get_it_on_play_logo_large.png", :width => "117"}/
      %p.content_b  
      %p.content_1
        %b Or
        scan this QR code:
      = image_tag("tutorial/qr_android.png", :height => '100', :alt =>"qrcode android")
      %p.content_b  
      %p.content_1
        %b Or
        open the following url
        = succeed "on" do
          %br/
        %br/
        = succeed "." do
          %a{:href => "https://fmsurvey.sg/afms"} https://fmsurvey.sg/afms
    .grid_4
      %p.title_1 iPhone
      %p.content_1
        FMS is a free application for your iOS device.
        = succeed "Download" do
          %br/
        = succeed "Apple" do
          %br/
      %p.content_b  
      %a{:href => "https://itunes.apple.com/sg/app/fm-survey/id604011160"}
        = image_tag("tutorial/app_store.png", :width => '117', :alt =>"app store logo")
      %p.content_b  
      %p.content_1
        %b Or
        scan this QR code:
      = image_tag("tutorial/qr_iphone.png", :height => '100', :alt =>"qrcode iphone")
      %p.content_b  
      %p.content_1
        %b Or
        open the following url
        = succeed "on" do
          %br/
        %br/
        = succeed "." do
          %a{:href => "https://fmsurvey.sg/ifms"} https://fmsurvey.sg/ifms
    .clear
    = link_to_function 'Next', "nextStep('step_1', 'step_2_android');", :class =>"button"
    = link_to_function 'Back', "back();", :class =>"button"
  #step_2_android.container_12.tutorial_steps{:style => "display:none"}
    .clear
    .grid_3
      %p.title_1
        %b Step 2
        — Registration
        = succeed "on" do
          %br/
      %br/
    .grid_3
      %p.content_1 The registration process takes two easy steps as shown in the pictures.
      %p.content_b  
      %p.content_1
        %b Note:
        = succeed "For" do
          %br/
    .grid_4
      = image_tag("tutorial/fms-mobile.png", :alt =>"fm_reg_1")
    .clear
    = link_to_function 'Next', "nextStep('step_2_android', 'step_3_android');", :class =>"button"
    = link_to_function 'Back', "back();", :class =>"button"
  #step_3_android.container_12.tutorial_steps{:style => "display:none"}
    .clear
    .grid_3
      %p.title_1
        %b Step 3
        — Start collecting data!
      %br/
    .grid_3
      %p.title_1 Tip 1
      %p.content_1
        Please keep the
        %br/
        %b application running
        for 14 days and
        = succeed "." do
          %b ensure that you are logged in
    .grid_3
      %p.title_1 Tip 2
      %p.content_1
        Run the application for at least
        %b 14 days
        and use the
        %b Activity Diary
        to provide us with additional information on 5 of them in order to qualify for
        %br/
        = succeed "." do
          %b your incentive
    .grid_3
      %p.title_1 Tip 3
      %p.content_1
        It is important to validate your data
        %b soon after you have collected it
        (while you still remember your activities for that day), instead of waiting until
        %br/
        the end of the 14 days.
    .clear
    .clear
    .grid_3
      %p.title_1
    .grid_3
      %p.title_1 Tip 4
      %p.content_1
        The data your smartphone collects about your location is not always precise,
        %br/
        so you may see on the map that your activities are in the wrong location. Dont't worry!
        %b You can change the location directly on the map!
    .grid_3
      %p.title_1 Tip 5
      %p.content_1
        We're working hard to improve battery performance, but you should plan on
        %b charging your battery throughout your day
        while running the app.
    .grid_2
      %p.content_b  
      %p.title_1 Thank you for your participation!
      = image_tag("smart/recruit_ok_2.png")
    .clear
    = link_to_function 'Back', "back();", :class =>"button"
:javascript
  curr_step = 'step_1';
  curr_brand = '';
  currentStepIDx = 1

  function back() {
  	if (curr_step == 'step_1'){
  		curr_brand = '';
  		return;
  	}
  	else{
  		partial_curr = curr_step.split('_');
  		prev = parseInt(partial_curr[1]) - 1;
  		if (prev == 1)
  			prev_state = "step_1";
  		else{
  			if (curr_brand == 'android' && prev==5){
  				prev=3;
  			}
  			prev_state = "step_"+prev+"_"+curr_brand;
  		}
  		nextStep(curr_step, prev_state);
  	}
  }

  function nextStep(current, next){
  	if (current == 'step_1'){
  		window.chosenOS = next.split('_')[2]
  		if (window.chosenOS == 'android' || window.chosenOS == 'iphone'){
  			//jQuery('#breadcrumb_step_1').css('width','30%')
  		} else {
  			//jQuery('#breadcrumb_step_1').css('width','30%')
  		}
  	}

  	if (next == 'step_1'){
  		window.chosenOS = undefined;
  	}

  	var prev = curr_step;

  	if(current == '')
  		current = curr_step;

  	parts = curr_step.split('_')
  	temp = parts[2];
  	if (temp)
  		curr_brand = temp;

  	curr_step = next;
  	console.log('#'+current)
  	jQuery('#'+current).fadeOut('slow', function(){
  		jQuery('#'+next).fadeIn('slow');
  	});

  	if (window.chosenOS != undefined){
  		which = window.chosenOS
  	} else {
  		which = undefined;
  	} 
  	nextParts = next.split('_');
  	currentStepIDx = parseInt(nextParts[1]);

  	//jQuery('.breadcrumb').hide();

  	console.log("currentStep",currentStepIDx)
  	if (currentStepIDx == 1){

  		jQuery('#breadcrumb_step_1').show();
  		jQuery('#breadcrumb_'+current).removeClass('current_step')
  		jQuery('#breadcrumb_step_1').removeClass('step_done').removeClass('before_current').addClass('current_step')
  		return;
  	}

  	console.log("currentStep",currentStepIDx)
  	var elmId;
  	for (var i=6; i>= 1; i--){
  		elmId = jQuery('#breadcrumb_step_'+i+(i>1&&i<6&&which!=undefined?('_'+which):''))
  		elmId.show();
  		elmId.removeClass('step_done')
  		elmId.removeClass('current_step')
  		elmId.removeClass('before_current')

  		if (currentStepIDx == 6){
  			if ((i==3 && window.chosenOS == 'android') || (i==3 && window.chosenOS == 'iphone')){
  				elmId.addClass('before_current')
  			}
  		}

  		if (i == currentStepIDx-1){
  			elmId.addClass('before_current')
  		} else if (i<currentStepIDx){
  			elmId.addClass('step_done')
  		} else if (i > currentStepIDx) {
  			//elmId.removeClass('step_done')
  			//elmId.removeClass('current_step')
  		} else {
  			elmId.addClass('current_step')
  		}
  	}
  }

  jQuery("a.gallery").fancybox();

app/views/pages/dashboard.html.haml
.clear
#password_reset.col-xs-12.col-md-6
  %p.title_2= I18n.t('profile.info')
  #feedback
    - if !flash[:notice].nil? and flash[:notice] != ''
      %p{:class => "<haml_loud"}
        "\#{flash[:class]}"  &gt; #{flash[:notice]}
  = form_for current_user, url: users_path, :html => {:class=>"form_login", :name=>"update_user_info"} do |f|
    .col-xs-8
      %table
        %tr
          %td
            %p.title_1
              = I18n.t('profile.info_username')
              \:
          %td
            = f.text_field :username
        %tr
          %td
            %p.title_1
              = I18n.t('profile.info_email')
              \:
          %td
            = f.label :email, current_user.email
    .col-xs-4
      = f.submit I18n.t('profile.info_save_btn'), :class => 'button pull-left'
  .clear
  #passwd_feedback
    - if !flash[:passwdupdated].nil? and flash[:passwdupdated] != ''
      %p{:class => "<haml_loud"}
        "\#{flash[:class]}"  &gt; #{flash[:passwdupdated]}
  = form_for current_user, url: update_password_users_path, html: {class: 'form_login', name: "change_user_password"}, method: :patch do |f|
    .col-xs-8
      %table
        %tr
          %td
            %p.title_1
              = I18n.t('profile.curr_passwd')
              \:
          %td= f.password_field :current_password
        %tr
          %td
            %p.title_1
              = I18n.t('profile.new_passwd')
              \:
          %td= f.password_field :password
        %tr
          %td
            %p.title_1
              = I18n.t('profile.conf_passwd')
              \:
          %td= f.password_field :password_confirmation
    .col-xs-4{:style => "padding-top: 10px;"}
      = f.submit I18n.t('profile.change_passwd_btn'), :class => 'button pull-left'
#travel_info.col-xs-12.col-md-3
  %p.title_2= I18n.t('profile.travel_info.title')
  %p.title_2 All tracked days
  %p
    = I18n.t('profile.travel_info.time')
    \: #{@travel_info_hash[:all_days][:total_time] || "nil"}
  %p
    = I18n.t('profile.travel_info.distance')
    \: #{@travel_info_hash[:all_days][:total_distance] || "nil"}
  - unless @travel_info_hash[:day].nil?
    .clear
    %p.title_2 Previous Day
    %p
      = I18n.t('profile.travel_info.time')
      \: #{@travel_info_hash[:day][:total_time]}
    %p
      = I18n.t('profile.travel_info.distance')
      \: #{@travel_info_hash[:day][:total_distance]}
#points.col-xs-12.col-md-3
  %p.title_2= I18n.t('profile.points.title')
  /
    <p class='title_1'><haml_loud> I18n.t(&#39;profile.points.level&#39;) </haml_loud>: <haml_loud> @level </haml_loud></p>
    <p class='title_1'><haml_loud> I18n.t(&#39;profile.points.tally&#39;) </haml_loud>: <haml_loud> @points </haml_loud></p>
  %p.title_1
    Pre-survey completed: #{current_user.completedPresurvey ? "yes" : "no"}
  %p.title_1
    = I18n.t('profile.points.days_collected')
    \: #{@days_collected}
  %p.title_1
    = I18n.t('profile.points.days_validated')
    \: #{@days_validated}
  %p.title_1
    Post-survey completed: #{current_user.completedPostSurvey ? "yes" : "no"}
.col-xs-12
  %h2 Frequent Places
  .clear
  = render 'partials/frequent_places'

app/views/pages/disclaimer.html.haml
.row{:style => "margin-top: 10px;"}
  #disclaimer.col-xs-offset-2.col-xs-8.well.text-justify
    %h3.text-center Disclaimer
    %h4
    %p
      The answers you provide to every section of this survey are considered confidential. At no place or time will we ask your name and all the records will be anonymised.
      %b
        %u We ask for the first four digits of the postcode of your home and office
      (if applicable) and will use it for market research and analysis purposes only. Your confidentiality is our top priority as such and the data will be collected and stored
      = succeed "." do
        %b
          %u in accordance with the Data Protection Act 1998
    %p Participation in the survey is completely voluntary and you are free to discontinue at any time. We will retain data collected from this survey on secure servers for current and future research.
    %p Kindly indicate whether your are willing to participate in this survey by clicking on the appropriate buttons below.
    %h3
      = button_to "Yes", pre_questionnaire_path, :method => :post, class:"btn btn-primary pull-left"
      = button_to "No", screenout_user_path(current_user), :method => :get, class:"btn btn-primary pull-right"
.stripes{:style => "margin-top: 10px;"}
:css
  #disclaimer p {
    text-align: justify;
  }

app/views/pages/home.html.haml
.row
  /
    <div class="col-md-4">
    <img alt='Activity Diary' src='/assets/maas/activity-diary-screenshot.png' title='Activity Diary'>
    <p>But what is an activity diary? The activity diary is an overview of your travel and non-travel activities. You can add or correct any of your activities and share with us some additional information. Don’t worry, all of this is kept confidentially (see our privacy policy)</p>
    </div>
  / Presurvey
  .col-xs-12.col-md-3{"data-intro" => "", "data-step" => "#{homepage_walkthrough_counter(:presurvey)}"}
    - if !current_user.completedPresurvey
      %p.phase
        = image_tag("smart/phase2.png", :alt =>"phase1" )
        = I18n.t('homepage.step_x') % {count: 1}
        \/
        %u= I18n.t('homepage.status.incomplete')
        %span.pull-right Day 1
      %p.title_2
        = link_to I18n.t('homepage.phase1.title'), pre_questionnaire_path
    - else
      %p.phase
        = image_tag("smart/phase2.png", :alt =>"phase1" )
        = I18n.t('homepage.step_x') % {count: 1}
        \/
        = succeed "\u{a0}" do
          %u= I18n.t('homepage.status.complete')
        = image_tag "maas/status_complete.png", size: "18x18"
        %span.pull-right Day 1
      %p.title_2
        = I18n.t('homepage.phase1.title')
    %p.content_2
      = I18n.t('homepage.phase1.duration')
    - if !current_user.completedPresurvey
      %p.content_i
        = I18n.t('homepage.phase1.description')
    - else
      %p.content_i
        %b= I18n.t('homepage.phase1.alt_description')
  / Stated Preference
  .col-xs-12.col-md-3{"data-intro" => "<h4>Finally on the 8th day check out the post-survey.</h4><h5>Here you will be able to learn about your travel statistics with our cool new mobility record tool. Then you will have the opportunity to have your say in the shaping of a new transportation service for London that combines all travel options (public transport, taxi, car clubs, Santander cycles) into easy to use plans for you.</h5>", "data-step" => "#{homepage_walkthrough_counter(:postsurvey)}"}
    - if not current_user.completedPostSurvey
      %p.phase
        = image_tag("smart/phase1.png", :alt =>"phase4" )
        = I18n.t('homepage.step_x') % {count: 4}
        %span.pull-right Day 9
      %p.title_2= link_to I18n.t('homepage.phase4.title'), new_stated_preference_experiment_path
    - else
      %p.phase
        = image_tag("smart/phase1.png", :alt =>"phase4" )
        = I18n.t('homepage.step_x') % {count: 4}
        \/
        = succeed "\u{a0}" do
          %u= I18n.t('homepage.status.complete')
        = image_tag "maas/status_complete.png", size: "18x18"
        %span.pull-right Day 9
      %p.title_2
        = I18n.t('homepage.phase4.title')
    %p.content_i
      = I18n.t('homepage.phase4.description')
    %p.content_i
      Make sure you do this on a PC or tablet - it may be a bit hard to see on your phone.
.clear.row
.clear.row
.col-xs-12{:style => "margin-top: 80px;"}
  .stripes
.clear
.row
  .col-xs-4.col-md-3
    = image_tag("smart/mobile.png", :alt =>"mobile" )
  .col-xs-4.col-md-3
    %p.title_1
      = I18n.t('homepage.confidentiality.title')
    %p.content_1
      = raw I18n.t('homepage.confidentiality.description') % {:privacy => link_to_privacy}
      \.
  .col-xs-4.col-md-3
    %p.title_1
      = I18n.t('homepage.support.title')
    %p.content_1= raw I18n.t('homepage.support.description') % {:faq => link_to_faqs, :support => link_to_support}
  .col-xs-8.col-xs-offset-2.col-md-3.col-md-offset-0
    %p  
    %p.title_1
      %b
        = I18n.t('homepage.thank_you')
/ Study By
.row{:style => "margin-top: 10px;"}
  .col-xs-2
    %h6 Study by:
  .col-xs-4
    = image_tag("maas/ucl-uei-logo.jpg", :alt =>"mobile" )
  .col-xs-3
    = image_tag("maas/its-logo.png", :alt =>"mobile" )
  .col-xs-3
    = image_tag("maas/smart-logo.png", :alt =>"mobile" )
.row{:style => "margin-top: 30px;"}
  .col-xs-2
    %h6 Supported by:
  .col-xs-3.col-md-2
    = image_tag("maas/work-shop-play-logo.jpg", :alt =>"mobile" )
/ Modal for Activity Diary screen-shot
#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title Activity Diary Example
      .modal-body
        %img{:alt => "Activity Diary", :src => "/assets/maas/activity-diary-screenshot.png", :title => "Activity Diary"}/
:javascript
  $('#activity-diary-screenshot').on('click', function() {
    $('#myModal').modal('show');
  });
:javascript
  // Show walk-through ONLY if not mobile!
  if (!(/Mobi/.test(navigator.userAgent))) {
    // var intro = introJs();
    // intro.start();
  }
:css
  .modal-dialog {
    width: 80%;
  }
:css
  .introjs-tooltip {
    text-align: center;
    max-width: none;
    background-color: #A01D21;
    color: white;
  }

  span.highlighter {
    background: #fff2a8;
    padding: 5px;
  }

app/views/pages/image_test.html.haml
= image_tag("maas/test.png", :alt =>"mobile" )

app/views/pages/new_home.de.html.haml
= javascript_include_tag "umove/resident_sp"
= form_tag(pages_survey_url, method: :post, id: "begin_survey") do
  .row{:style => "margin-top: 10px;"}
    #home_page.col-xs-offset-1.col-xs-10.well.text-justify
      %h4.text-center
        %b Diese Umfrage ist Teil des Europäischen Horizon2020 Projekts MaaS4EU
      %h4
      %p In dieser Umfrage geht es um ein neues Mobilitätsangebot, welches bald in Ihrer Stadt verfügbar sein wird. Um Ihnen den bestmöglichen Service anbieten zu können, führen wir diese Umfrage durch um etwas über Ihre Vorlieben und Bedürfnisse bezüglich Mobilität zu erfahren.
      %p Nach erfolgreicher Beendigung der Umfrage können Sie an einem Gewinnspiel teilnehmen und Freikarten und reduzierte Tickets für verschiedene Verkehrsmittel gewinnen. Um am Gewinnspiel teilzunehmen, geben Sie bitte Ihre E-Mail an:
      %p.text-center.col-md-offset-3.col-md-9{:style => "margin-top: 0px;"}
        %span.col-md-3 E-Mail:
        %span.col-md-6{:style => "margin-left: -50px;"}
          = text_field_tag :user_email, nil, class: "form-control", placeholder: "Geben sie ihre E-Mailadresse ein"
      %p.text-right Wir bedanken uns für Ihre Teilnahme und Ihre ehrlichen Antworten.
      %p
        %i
          Ihre Daten sind nach der EU Datenschutzgrundverordnung geschützt. Ihre Daten sind anonymisiert und werden nur zu projektbezogenen Zwecken benutzt. Für mehr Informationen lesen Sie die
          %a{:href => "/docs/policy.pdf"}
            %u Privacy Policy
          und die
          = succeed "." do
            %a{:href => "/docs/faq_maas.pdf"}
              %u FAQ
      %h5.row.text-center
        %span.col-md-6 Bitte wählen Sie Ihre Sprache für die Umfrage aus
        %span.col-md-3
          = select_tag "lux_language", options_for_select(@lux_language_options, 2), class: "form-control"
      %h3
        = hidden_field_tag "city_id", @city
        = button_tag type: 'submit', class: 'btn-lg btn-warning pull-right' do
          Umfrage starten
/ end of form
.stripes{:style => "margin-top: 10px;"}
:css
  #home_page p {
    font-family: Helvetica;
    font-size: 16px;
    /*text-align: justify;*/
  }

  #home_page .title_1 {
    font-family: Helvetica;
  }

  label {
    font-weight: normal;
  }

app/views/pages/new_home.fr.html.haml
= javascript_include_tag "umove/resident_sp"
= form_tag(pages_survey_url, method: :post, id: "begin_survey") do
  .row{:style => "margin-top: 10px;"}
    #home_page.col-xs-offset-1.col-xs-10.well.text-justify
      %h4.text-center
        %b Cette enquête fait partie du projet européen de recherche H2020 MaaS4EU
      %h4
      %p Il s'agit d'une enquête sur un nouveau service de mobilité qui sera disponible dans votre ville (région) bientôt. Pour être en mesure de vous fournir les meilleurs services, nous menons cette enquête pour comprendre vos préférences de voyage et vos besoins.
      - if @city_id != City::OXFORDSHIRE
        %p Une fois que vous avez terminé l'enquête complète, vous serez inscrit dans un tirage au sort pour gagner des billets gratuits et à prix réduit pour différents modes de transport. Pour entrer le tirage au sort, veuillez fournir votre courriel:
        %p.text-center.col-md-offset-3.col-md-9{:style => "margin-top: 0px;"}
          %span.col-md-3 Email:
          %span.col-md-6{:style => "margin-left: -50px;"}
            = text_field_tag :user_email, nil, class: "form-control", placeholder: "Entrez votre adresse email"
      %p.text-right Nous apprécions vraiment votre participation et vos réponses honnêtes.
      %p
        %i
          Vos données sont protégées selon la législation européenne sur la protection et la confidentialité des données personnelles. Vos données sont rendues anonymes et ne seront utilisées qu'aux fins de ce projet. Veuillez lire la
          %a{:href => "/docs/policy.pdf"}
            %u politique de confidentialité
          et la
          %a{:href => "/docs/faq_maas.pdf"}
            %u FAQ
          pour plus d'informations.
      - if @city_id == City::TURIN
        %h5.row.text-center
          %span.col-md-6 Sélectionnez la langue de votre sondage
          %span.col-md-3
            = select_tag "lux_language", options_for_select(@lux_language_options, 3), class: "form-control"
      %h3
        = hidden_field_tag "city_id", @city
        = button_tag type: 'submit', class: 'btn-lg btn-warning pull-right' do
          Start the survey
/ end of form
.stripes{:style => "margin-top: 10px;"}
:css
  #home_page p {
    font-family: Helvetica;
    font-size: 16px;
    /*text-align: justify;*/
  }

  #home_page .title_1 {
    font-family: Helvetica;
  }

  label {
    font-weight: normal;
  }

app/views/pages/overview.html.haml
.row
  .col-md-12.text-center
    %h4{:style => "font-family: Calibri;"} Thank you for taking our survey! These are the steps of the survey:
    / <haml_loud> image_tag(&quot;maas/overview-2.png&quot;, :alt =&gt;&quot;mobile&quot; ) </haml_loud>
    = image_tag("maas/overview-3.jpg", :alt =>"mobile", usemap: "#overview-map")
    %map{:name => "overview-map"}
      %area{:alt => "Pre-Survey", :coords => "50,30,250,230", :href => "/pre_questionnaire", :shape => "rect"}/
  .col-md-12.text-center
    = link_to "Start Step 1", pre_questionnaire_path, class: "btn btn-success"

app/views/pages/tab_3_3.html.haml
.row{:style => "margin-top: 10px;"}
  .col-md-12
    %h3 STEP 3
    %table.table
      %tr
        %th Number of Validated Days
        %th Mode Used
        %th Activity Purpose
      %tr
        %td 10
        %td
          %table.stats{:style => "padding: 10px;"}
            %tr
              %td
                %b Car as a driver
              %td 30%
            %tr
              %td
                %b Car as a passenger
              %td 10%
            %tr
              %td
                %b Taxi
              %td 20%
            %tr
              %td
                %b Ride-hailing (Uber)
              %td 15%
            %tr
              %td
                %b Others
              %td 30%
        %td
          %table.stats{:style => "padding: 10px;"}
            %tr
              %td
                %b Work
              %td 60%
            %tr
              %td
                %b Grocery Shopping
              %td 15%
            %tr
              %td
                %b Leisure
              %td 25%
.stripes{:style => "margin-top: 10px;"}
:css
  table.stats td {
    padding: 5px;
  }

  .section_title {
    font-size: 20px;
  }