config/routes.rb
Rails.application.routes.draw do
  get 'sections/show'

  resources :pre_survey_travel_patterns
  resources :pre_surveys do
    collection do
      get :new_tourist
      get :new_resident
    end
  end

  # SP Experiment
  resources :sp_experiments do
    resource :activity_choices
    resource :day_to_day_learnings
    resources :day_choices
  end

  # Pre-survey
  resources :pre_survey_journey_planner_characteristics
  resources :pre_survey_private_mobility_characteristics
  # resources :pre_survey_household_characteristics
  resources :pre_survey_socio_economic_characteristics
  match 'pre_questionnaire' => 'pre_survey_socio_economic_characteristics#new', :via => [:post, :get]
  match 'finish_presurvey' => 'pre_survey_journey_planner_characteristics#finish_presurvey', :via => [:post, :get]
  
  resources :tests

  # Users section
  resource :users, only: [:new, :create, :update] do
    patch :update_password, on: :member
    post :submitIgnorePopup
    post :acknowledge_warning
    get :dismiss_timezone_warnings
    get :update_wsp_email
    get :new_wsp
    get :sync_umove
  end

  resources :users do
    member do
      get :screenout
    end
  end

  get 'users/:study/new' => 'users#new', as: :new_users_for_study
  post 'users/:study' => 'users#create', as: :users_for_study

  resource :user_session, only: [:create, :destroy] do
    post :change_timezone
  end

  namespace :activations do
    get :new
    get ":activation_code", action: :create
    post :resend, as: :resend
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :sections do
    get :next_section, on: :collection
  end

  # get "/wsp_register" => "users#new_wsp"

  # Static pages and AD section

  namespace :pages do
    get :home
    get :new_home
    get :thankyou
    get :newuser
    get :calendar
    post :calendar
    get :feedback_feedback
    get :consent
    get :contacts
    get :faqs
    get :dashboard
    get :support
    post :support_submit
    patch :accept_consent
    patch :deactivate_user
    # root to: :index # BEFORE
    get :info
    get :overview
    get :image_test
    root action: :index
    get :wsp
    get :disclaimer
    get :statistics
    get :summarise
    get :backoffice_container
    get :backoffice
    get :tab_1
    get :tab_2
    # get :tab_3
    get :tab_3_1
    get :tab_3_2
    get :tab_3_3
    get :gateway
    post :survey
  end

  match "/delayed_job" => DelayedJobWeb, anchor: false, via: [:get, :post]#, constraints: AdminConstraint.new

  root :to => 'pages#survey'
end

app/views/layouts/_header_frontend.html.haml
:javascript
  var smart;
  if (smart === undefined) {
  	smart = {};
  }
  if (smart.instances === undefined){
  	smart.instances = {};
  }
  
  if (!window.console) window.console = {};
  if (!window.console.log) window.console.log = function () { };
= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js"
= javascript_include_tag "vendor", "common"
= csrf_meta_tags

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Survey
    = stylesheet_link_tag    "common", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/backoffice_layout.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "Happy Mobility Survey Backoffice", :name => "description"}/
    %meta{:content => "SMART-FM", :name => "author"}/
    %link{:href => "/assets/smart/favicon3.ico", :rel => "icon", :type => "image/gif"}/
    %title HMSurvey - Backoffice
    = stylesheet_link_tag "backofficeCSS", :media => 'all'
    /[if IE ]
      <link rel="stylesheet" type="text/css" href="/stylesheets/ink-ie.css">
    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    / Google Maps JS on top, needs to be loaded first
    %script{:src => "https://maps.google.com/maps/api/js?sensor=true&libraries=geometry", :type => "text/javascript"}
    = javascript_include_tag "vendor", "backofficeJS"
    = csrf_meta_tags
    :javascript
      var smart;
      if (smart === undefined) {
      	smart = {};
      }
      if (smart.instances === undefined){
      	smart.instances = {};
      }
    = yield :scripts
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-34220786-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
  / FancyBox Hack
  %body
    #hidden_clicker{:style => "display:none"}
      %a#hiddenclicker{:href => "#"} Hidden Clicker
    .alert_container
    #wrap
      .container
        .row
          / header: logo + feedback + menu
          .col-xs-12.col-md-4.hidden-xs
            = link_to image_tag("smart/logo-hms.png", :alt =>"logo" ), :root, :class =>"image_link"
          /
            <div class="col-md-2">
            <haml_loud> link_to image_tag(&quot;smart/feedback_fms.png&quot;, :alt =&gt;&quot;feedback&quot; ), :root, :class =&gt;&quot;image_link&quot; </haml_loud>
            </div>
          .col-xs-12.col-md-8.pull-right.header_right
            .menus
              .menu_user
                .menu_user2
                  - if logged_in?
                    %ul
                      .col-xs-6.col-md-5.col-md-offset-3.control-narrow
                        %li.time_zone_panel_container
                          = render "partials/change_timezone"
                        %li= current_user.time_zone
                      .col-xs-6.col-md-4.control-narrow
                        - if current_user.has_role? 'admin'
                          %li= link_to "Backoffice", backoffice_root_path
                        - if current_user.has_role? 'helper'
                          %li= link_to "Call center", backoffice_helpcenter_root_path
                        - if current_user.has_role? 'guardian'
                          %li
                            %a{:href => "/backoffice/guardian/"} Guardian Center
                        %li= link_to I18n.t('layout.logout'), user_session_path, :method => :delete
                      .col-xs-12.col-md-12.control-narrow
                        %li.row
                          = link_to I18n.t('layout.welcome', :username => "#{current_user.name}"), pages_dashboard_path
                        - else
                          %ul
                / .menu_user
                .menu_main
                  %ul
                    %li= link_to I18n.t('layout.contacts'), pages_contacts_path, :class => ("current" unless url_for() != "/pages/contacts")
                    - if logged_in?
                      %li= link_to I18n.t('layout.support'), pages_support_path
                    - if logged_in?
                      - if !current_user.completedPresurvey
                        %li= link_to I18n.t('layout.presurvey'), attempt_presurvey_path, :class => ("current" unless (request.url =~ /\/surveys\/presurvey/).nil? )
                      - else
                        %li= link_to I18n.t('layout.adiary'), report_root_path, :class => ("current" unless url_for() != "/report")
                      %li= link_to 'DASHBOARD', pages_dashboard_path
                      - if current_user.finished[0]
                        %li
                      / <li><haml_silent></haml_silent></li>
                      %li= link_to I18n.t('layout.home'), pages_home_path, :class => ("current" unless (url_for() != "/pages/home" and url_for() != "/pages/home_mobile"))
                    - else
                      %li= link_to  I18n.t('layout.home'), pages_root_path, :class => ("current" unless url_for() != "/pages/newuser")
                / .menu_main
              / .menus
              .clear
            / .col-md-4
          / .row
          %br/
          .row
            .col-md-12.stripes
          %br/
          .row
            = yield
        / /.container
      / /wrap
      %footer.footer
        .container.credit
          = link_to image_tag("smart/smart_logo.png", :alt =>"smart" ), "http://smart.mit.edu", :target => "_blank", :class =>"image_link"
      /
        Bootstrap core JavaScript
        \==================================================
      / Placed at the end of the document so the pages load faster

app/views/layouts/bootstrap_generator.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Starter Template for Bootstrap
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <haml_loud> javascript_include_tag &quot;https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js&quot;, &quot;https://oss.maxcdn.com/respond/1.4.2/respond.min.js&quot; </haml_loud>
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          = msg
      = yield

app/views/layouts/embed.html.haml
!!!
/[if IE 7] <html class="ie7" lang="en">
/ [if !(IE 7)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    / <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, initial-scale=1.0">
    %meta#mvp{:content => "height=device-height, width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "HARMONY", :name => "application-name"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "University College London - Energy Institute", :name => "author"}/
    %link{:href => "/assets/umove/favicon.ico", :rel => "icon", :type => "image/gif"}/
    %title HARMONY
    = stylesheet_link_tag "pre-common", :media => 'all'
    = stylesheet_link_tag "timeline", :media => 'all'
    = stylesheet_link_tag "common", :media => 'all'
    = stylesheet_link_tag "rails_bootstrap_forms", :media => 'all'
    = stylesheet_link_tag "introjs.min", :media => 'all'
    = csrf_meta_tags
    = stylesheet_link_tag "hint.min.css"
    = render :partial => "/layouts/header_frontend"
  %body
    #wrapper.container
      #header.row
        / header: logo + feedback + menu
        .col-md-3.col-sm-4.hidden-xs
        / end .grid_4 logo
        /
          <div class="grid_2 people_holder">
          <a href="<haml_silent></haml_silent>" class="image_link" ><img id="people" src="/assets/smart/feedback_fms.png" alt="feedback"/></a>
          </div>
        / end .grid_4 feedback
        .col-xs-4.col-sm-2.col-md-2.header_right
          .menus
            .menu_user
              .menu_user2
        / end .grid_4 feedback
        / fim do header
      #maincontent.row
        - flash[:class] ||= "content_feedback"
        .col-xs-12
          #flash_messages
            - if flash[:notice]
              %p{:class => "<haml_loud"}
                flash[:class] &gt;#{flash[:notice]}
            - yield :flash_messages
          .stripes
        / <div class="clear"></div>
        = yield :topselection
        = yield :secondselection
        .clear.hidden-xs
        / <div class="clear"></div>
        #bottom_selection.row
          = yield :bottomleft
          = yield :bottomright
        = yield
      / end .container_12
      / Footer
    / end of wrapper
    - if false
      #helpbutton
        %p  
        %a{:href => "#helpscreen"} Need Help?
    #sDialog.feedbackDialog.shadow{:style => "display:none"}
      .xClose X
      .container
        #onlineHelp.slot.ruler_r
        #scheduleSession.slot
          %h3 Schedule a session
          %p We encourage you to schedule a live session with us so we can give you a first introduction to our interface.
          .sessionStatus
    / TEMPLATES
    %script#template_supportScreen_online{:type => "text/html"}
      :cdata
        <h3>Need Help?</h3>
        <p class="helpcenter_status">
        \#{image_tag("smart/helpcenter_online.png", :alt =>"Helpcenter online", :title => "Online" )}
        Status: Online
        </p>
        <p>Anything we can help you with?</p>
        <p>Feel free to chat with us.</p>
        <p><a href="#" class="button_start_chat">Start Chat</a></p>
    %script#template_supportScreen_offline{:type => "text/html"}
      :cdata
        <h3>Need Help?</h3>
        <p class="helpcenter_status">
        \#{image_tag("smart/helpcenter_offline.png", :alt =>"Helpcenter offline", :title => "Offline" )}
        Status: Offline
        </p>
        <p>Unfortunately at this moment we do not have anyone available to assist you.</p>
        <p>Feel free to contact us by email at fmsurvey@smart.mit.edu.</p>
    %script#template_supportScreen_schedule{:type => "text/html"}
      :cdata
        <p class="scheduleInfo">You have a schedule session on <span class="date"></span> at <span class="time"></span>.</p>
        <p><a href="/pages/calendar" target="_blank" class="button_reschedule"> Reschedule </a></p>
    %script#template_supportScreen_noschedule{:type => "text/html"}
      :cdata
        <p><a href="/pages/calendar" target="_blank" class="button_schedule"> Schedule a Session </a></p>
    / SCRIPTS AFTER HERE
    = yield :scripts

app/views/layouts/javascript_test.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QUnit Tests
    %script{:src => "https://maps.google.com/maps/api/js?sensor=false&libraries=geometry", :type => "text/javascript"}
    = render :partial => "/layouts/header_frontend"
    = stylesheet_link_tag 'vendor/qunit'
    = javascript_include_tag 'vendor/qunit'
    %script{:language => "Javascript"}
      :cdata
        $(document).ready(function() {
        \#{yield}
        });
  %body
    %h1#qunit-header QUnit example
    %h2#qunit-banner
    #qunit-testrunner-toolbar
    %h2#qunit-userAgent
    %ol#qunit-tests
    #qunit-fixture test markup, will be hidden

app/views/layouts/presurvey.html.haml
- content_for :scripts do
  = surveyor_includes
.col-xs-3
  %p.title_2.survey_title
    = yield :survey_title
    %br/
    = yield :survey_section
  %p.title_3= yield :survey_section_title
  %p.content_i= yield :survey_section_description
  %p.content_2 (5-10 minutes)
  %p.content_b  
  = yield :survey_section_icon
/ questions
.col-xs-9.presurvey
  = yield
- parent_layout "smart"

app/views/layouts/smart.html.haml
!!!
/[if IE 7] <html class="ie7" lang="en">
/ [if !(IE 7)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    / <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, initial-scale=1.0">
    %meta#mvp{:content => "height=device-height, width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "HARMONY", :name => "application-name"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "University College London - Energy Institute", :name => "author"}/
    %link{:href => "/assets/umove/favicon.ico", :rel => "icon", :type => "image/gif"}/
    %title HARMONY
    = stylesheet_link_tag "pre-common", :media => 'all'
    = stylesheet_link_tag "timeline", :media => 'all'
    = stylesheet_link_tag "common", :media => 'all'
    = stylesheet_link_tag "rails_bootstrap_forms", :media => 'all'
    = stylesheet_link_tag "introjs.min", :media => 'all'
    = csrf_meta_tags
    = stylesheet_link_tag "hint.min.css"
    = render :partial => "/layouts/header_frontend"
  %body
    #wrapper.container
      #header.row
        / header: logo + feedback + menu
        .col-md-3.col-sm-4.hidden-xs
        - if current_page?(root_path) or current_page?(new_wsp_users_path) or current_page?(pages_disclaimer_path) or current_page?(pages_statistics_url) or @hide_header
          .col-md-3.col-sm-3{:style => "margin-top: 75px;"}
          .col-md-3.col-sm-3{:style => "margin-top: 75px;"}
        - else
          .col-md-3.col-sm-3{:style => "margin-top: 75px;"}
            %h4{:style => "padding:0px; margin:0px;"}
            %p.title_2{:style => "font-size:17px; padding:0px; margin:0px;"}
              = t("pre_survey.header_title")
              - if @survey_progress.blank? or @survey_progress == 100
                %span= image_tag "maas/status_complete.png", size: "18x18"
              %br/
              = render "pre_questionnaire/progress", value: (@survey_progress || 100)
          - if @label
            .col-md-2{:style => "margin-top: 125px;"}
              %span
                %b
                  Task #{@label}
        / end .grid_4 logo
        /
          <div class="grid_2 people_holder">
          <a href="<haml_silent></haml_silent>" class="image_link" ><img id="people" src="/assets/smart/feedback_fms.png" alt="feedback"/></a>
          </div>
        / end .grid_4 feedback
        .col-xs-4.col-sm-2.col-md-2.header_right
          .menus
            .menu_user
              .menu_user2
        / end .grid_4 feedback
        / fim do header
      #maincontent.row
        - flash[:class] ||= "content_feedback"
        .col-xs-12
          #flash_messages
            - if flash[:notice]
              %p{:class => "<haml_loud"}
                flash[:class] &gt;#{flash[:notice]}
            - yield :flash_messages
          .stripes
        / <div class="clear"></div>
        = yield :topselection
        = yield :secondselection
        .clear.hidden-xs
        / <div class="clear"></div>
        #bottom_selection.row
          = yield :bottomleft
          = yield :bottomright
        = yield
      / end .container_12
      / Footer
    / end of wrapper
    %footer#footer
      .container.smart_logo
        .row
    - if false
      #helpbutton
        %p  
        %a{:href => "#helpscreen"} Need Help?
    #sDialog.feedbackDialog.shadow{:style => "display:none"}
      .xClose X
      .container
        #onlineHelp.slot.ruler_r
        #scheduleSession.slot
          %h3 Schedule a session
          %p We encourage you to schedule a live session with us so we can give you a first introduction to our interface.
          .sessionStatus
    / TEMPLATES
    %script#template_supportScreen_online{:type => "text/html"}
      :cdata
        <h3>Need Help?</h3>
        <p class="helpcenter_status">
        \#{image_tag("smart/helpcenter_online.png", :alt =>"Helpcenter online", :title => "Online" )}
        Status: Online
        </p>
        <p>Anything we can help you with?</p>
        <p>Feel free to chat with us.</p>
        <p><a href="#" class="button_start_chat">Start Chat</a></p>
    %script#template_supportScreen_offline{:type => "text/html"}
      :cdata
        <h3>Need Help?</h3>
        <p class="helpcenter_status">
        \#{image_tag("smart/helpcenter_offline.png", :alt =>"Helpcenter offline", :title => "Offline" )}
        Status: Offline
        </p>
        <p>Unfortunately at this moment we do not have anyone available to assist you.</p>
        <p>Feel free to contact us by email at fmsurvey@smart.mit.edu.</p>
    %script#template_supportScreen_schedule{:type => "text/html"}
      :cdata
        <p class="scheduleInfo">You have a schedule session on <span class="date"></span> at <span class="time"></span>.</p>
        <p><a href="/pages/calendar" target="_blank" class="button_reschedule"> Reschedule </a></p>
    %script#template_supportScreen_noschedule{:type => "text/html"}
      :cdata
        <p><a href="/pages/calendar" target="_blank" class="button_schedule"> Schedule a Session </a></p>
    / SCRIPTS AFTER HERE
    = yield :scripts

app/views/layouts/surveyor_custom.html.haml
- content_for :scripts do
  = surveyor_includes
/ questions
.col-xs-12.survey
  = yield
- parent_layout "smart"

app/views/layouts/umove.html.haml
!!!
/[if IE 7] <html class="ie7" lang="en">
/ [if !(IE 7)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    / <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, initial-scale=1.0">
    %meta#mvp{:content => "height=device-height, width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "HARMONY", :name => "application-name"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "University College London - Energy Institute", :name => "author"}/
    %link{:href => "/assets/umove/favicon.ico", :rel => "icon", :type => "image/gif"}/
    %title
      HARMONY
      - if not @selected_date.nil?
        \- Activity Diary on #{@selected_date}
    = stylesheet_link_tag "pre-common", :media => 'all'
    = stylesheet_link_tag "timeline", :media => 'all'
    = stylesheet_link_tag "common", :media => 'all'
    = stylesheet_link_tag "rails_bootstrap_forms", :media => 'all'
    = stylesheet_link_tag "introjs.min", :media => 'all'
    = csrf_meta_tags
    = stylesheet_link_tag "hint.min.css"
    = render :partial => "/layouts/header_frontend"
  %body
    #wrapper.container
      #header.row
        .col-md-3.col-sm-4.hidden-xs
        - if current_page?(root_path) or current_page?(new_wsp_users_path) or current_page?(pages_disclaimer_path)
          .col-md-3.col-sm-3{:style => "margin-top: 75px;"}
          .col-md-3.col-sm-3{:style => "margin-top: 75px;"}
        - else
          .col-md-3.col-sm-3{:style => "margin-top: 75px;"}
            %h4{:style => "padding:0px; margin:0px;"}
              - if controller_name != 'sp_experiments'
                %p.title_2{:style => "font-size:17px; padding:0px; margin:0px;"}
              - else
                %p.title_4{:style => "font-size:17px; padding:0px; margin:0px;"}
              1. Individual Survey
              - if @pq_progress.blank? or @pq_progress == 100
                %span= image_tag "maas/status_complete.png", size: "18x18"
              %br/
              = render "pre_questionnaire/progress", value: (@pq_progress || 100)
          .col-md-4.col-sm-3{:style => "margin-top: 75px;"}
            %h4{:style => "padding:0px; margin:0px;"}
              - if controller_name == 'sp_experiments'
                %p.title_2{:style => "font-size:17px; padding:0px; margin:0px;"}
              - else
                %p.title_4{:style => "font-size:17px; padding:0px; margin:0px;"}
              2. New Mobility Service Survey
              - if @sp_progress == 17
                %span= image_tag "maas/status_complete.png", size: "18x18"
              %br/
              .progress
                .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{sp_progress_to_percent(@sp_progress)}", :role => "progressbar", :style => "width: #{sp_progress_to_percent(@sp_progress)}%;"}
                  = sp_progress_to_percent(@sp_progress)
                  \%
          - if @label
            .col-md-2{:style => "margin-top: 125px;"}
              %span
                %b
                  Task #{@label}
        / end .grid_4 logo
        /
          <div class="grid_2 people_holder">
          <a href="<haml_silent></haml_silent>" class="image_link" ><img id="people" src="/assets/smart/feedback_fms.png" alt="feedback"/></a>
          </div>
        / end .grid_4 feedback
        .col-xs-4.col-sm-2.col-md-2.header_right
          .menus
            .menu_user
              .menu_user2
        / end .grid_4 feedback
        / fim do header
      #maincontent.row
        - flash[:class] ||= "content_feedback"
        .col-xs-12
          #flash_messages
            - if flash[:notice]
              %p{:class => "<haml_loud"}
                flash[:class] &gt;#{flash[:notice]}
            - yield :flash_messages
          .stripes
        / <div class="clear"></div>
        = yield :topselection
        = yield :secondselection
        .clear.hidden-xs
        / <div class="clear"></div>
        #bottom_selection.row
          = yield :bottomleft
          = yield :bottomright
        = yield
      / end .container_12
      / Footer
    / end of wrapper
    %footer#footer
      .container.smart_logo
        .row
    - if false
      #helpbutton
        %p  
        %a{:href => "#helpscreen"} Need Help?
    #sDialog.feedbackDialog.shadow{:style => "display:none"}
      .xClose X
      .container
        #onlineHelp.slot.ruler_r
        #scheduleSession.slot
          %h3 Schedule a session
          %p We encourage you to schedule a live session with us so we can give you a first introduction to our interface.
          .sessionStatus
    / TEMPLATES
    %script#template_supportScreen_online{:type => "text/html"}
      :cdata
        <h3>Need Help?</h3>
        <p class="helpcenter_status">
        \#{image_tag("smart/helpcenter_online.png", :alt =>"Helpcenter online", :title => "Online" )}
        Status: Online
        </p>
        <p>Anything we can help you with?</p>
        <p>Feel free to chat with us.</p>
        <p><a href="#" class="button_start_chat">Start Chat</a></p>
    %script#template_supportScreen_offline{:type => "text/html"}
      :cdata
        <h3>Need Help?</h3>
        <p class="helpcenter_status">
        \#{image_tag("smart/helpcenter_offline.png", :alt =>"Helpcenter offline", :title => "Offline" )}
        Status: Offline
        </p>
        <p>Unfortunately at this moment we do not have anyone available to assist you.</p>
        <p>Feel free to contact us by email at fmsurvey@smart.mit.edu.</p>
    %script#template_supportScreen_schedule{:type => "text/html"}
      :cdata
        <p class="scheduleInfo">You have a schedule session on <span class="date"></span> at <span class="time"></span>.</p>
        <p><a href="/pages/calendar" target="_blank" class="button_reschedule"> Reschedule </a></p>
    %script#template_supportScreen_noschedule{:type => "text/html"}
      :cdata
        <p><a href="/pages/calendar" target="_blank" class="button_schedule"> Schedule a Session </a></p>
    / SCRIPTS AFTER HERE
    = yield :scripts